### ISSUE TITLE
Saved value carries over to new input and inserts itself when handleCancel is called

### ISSUE THREAD

**Issue by brandonparis** [alioguzhan/react-editext#103] opened 2021-01-12 00:07 UTC
**Describe the bug**

When I update an item on the page it saves correctly and I see the correct (new) input value. In my application I have the value of the editext controlled by props. When I go to change those props (basically select a new item with different content) I also get the correct value for the input. However, if that input value happens to be an empty string, which in my case happens a lot, and I go to edit that empty string and then cancel that editing, I get the _previous_ value inserted into the input.

**Expected behavior**
That the cancel function would store the original info not the previously _savedValue_

https://codesandbox.io/s/cocky-stonebraker-etrt1?file=/src/index.js

So the steps to reproduce are....

Edit the text and save --> Then, hit the "Select new string" button --> Edit this text --> Cancel editing of this text. You should see the old string put in the input value.

**Comment by harshilparmar** [comment] 2021-01-12 03:32
And one more thing to add can't perform `select new string` after clicking cancel once.

@alioguzhan  I would like to see this issue 😀

**Comment by alioguzhan** [comment] 2021-01-14 12:35
Hey, Thanks for reporting this issue. I will look into that in a day or so. I will update here.  @brandonparis 

Hey, I don't understand the problem :( Can you elaborate on it in a new issue? Thanks! @harshilparmar

**Comment by alioguzhan** [comment] 2021-01-16 09:40
Yes, I can reproduce this issue. I started to work on this. It is probably because the empty string is considered as `falsy` value, so we ignore that and revert it to the previous one.

**Comment by alioguzhan** [comment] 2021-01-16 09:45
We can also reproduce that at [examples page](https://alioguzhan.github.io/react-editext/#save-on-enter):

![editext-bug](https://user-images.githubusercontent.com/1928541/104808656-c1364f80-57f8-11eb-984b-d980e4d12db9.gif)

**Comment by alioguzhan** [comment] 2021-01-16 10:03
Ok, we can fix this problem by not treating `empty strings` as false values. 

BUT, I am not sure if this is the correct approach. Because even the language itself tells that `empty strings are falsy values`.  See the [related section in the specification](https://www.ecma-international.org/ecma-262/11.0/index.html#sec-toboolean), please.

I am sure there are people using this component as it is now. Otoh, your case is also pretty valid. It is totally fine to keeping empty strings as they are. We can enable this by adding a new property like `accept empty string`. What do you think?

**Comment by alioguzhan** [comment] 2021-01-16 10:05
Or we can implement this as the default behavior. I need to check other libraries/components to see some references.

**Comment by alioguzhan** [comment] 2021-01-16 11:40
@brandonparis Can you please verify that the problem is solved:

https://deploy-preview-104--react-editext.netlify.app/

**Comment by brandonparis** [comment] 2021-01-18 18:58
@alioguzhan having a hard time figuring out how to test. How do you recommend I test the new build out, as I don't see a place in the deployed app where I can test the specific case out.

**Comment by alioguzhan** [comment] 2021-01-19 08:56
hey @brandonparis , can you please update your `package.json` as below:

```json
"dependencies": {
    "react-editext": "alioguzhan/react-editext#fix-empty-string-bug"
}
``` 

This way, you should be able to install the package from a specific branch or commit. Please let me know if this works or not.

**Comment by alioguzhan** [comment] 2021-01-19 09:01
For reference, you can see different options to install a package from URL or Github repository:

https://docs.npmjs.com/cli/v6/configuring-npm/package-json#git-urls-as-dependencies

**Comment by brandonparis** [comment] 2021-01-19 14:28
> hey @brandonparis , can you please update your `package.json` as below:
> 
> ```json
> "dependencies": {
>     "react-editext": "alioguzhan/react-editext#fix-empty-string-bug"
> }
> ```
> 
> This way, you should be able to install the package from a specific branch or commit. Please let me know if this works or not.

Got it, thank you. I'll test it out today and let you know.

**Comment by brandonparis** [comment] 2021-01-19 14:50
@alioguzhan confirmed that it's still an issue unfortunately. 

<img width="544" alt="Screen Shot 2021-01-19 at 7 49 09 AM" src="https://user-images.githubusercontent.com/17344791/105050372-f1fdcb00-5a2a-11eb-97af-6199f84627e0.png">

Made sure the new code is running too.

**Comment by alioguzhan** [comment] 2021-01-19 21:49
OK, I will investigate that. Stay tuned...

**Comment by alioguzhan** [comment] 2021-01-24 11:06
I could not find a way to add a package's specific branch to a Codesandbox project. So I am going to merge this fix to the master so we can test it on Codesandbox. I couldn't reproduce your issue after the fix but I will try it with your Codesandbox example. Once we agree on it is fixed, I will send a new release to the npm. @brandonparis

**Comment by alioguzhan** [comment] 2021-01-24 12:34
Ok, I merged the latest PR and the example web site is updated. But I could not reproduce the problem. Can you please try this example here:

https://alioguzhan.github.io/react-editext/#edit-by-default

Please try your scenario and let me know the details.  Thanks, @brandonparis

**Comment by brandonparis** [comment] 2021-01-25 18:46
@alioguzhan I'm not sure there's an example on that page that matches the situation exactly. 

Take a look at this codesandbox: https://codesandbox.io/s/purple-tdd-0pi9m

Using the steps here you should be able to reproduce easily

Edit the text and save --> Then, hit the "Select new string" button --> Edit this text --> Cancel editing of this text. You should see the old string put in the input value.

**Comment by alioguzhan** [comment] 2021-02-02 10:54
Hey @brandonparis,

I am having progress on solving the issue. And I updated one of the examples so that we can reproduce your scenario. Can you please check it from the below link:

https://deploy-preview-105--react-editext.netlify.app/#edit-by-default

There is still a small issue remaining: Once you set the value via button, you cannot re-set it to the same value by clicking to the button. But the old input value shouldn't appear once you cancel the editing.

**Comment by brandonparis** [comment] 2021-02-02 16:39
@alioguzhan yep I'll try to get that testing done today, thanks for cranking on this.

**Comment by brandonparis** [comment] 2021-02-02 16:49
@alioguzhan it looks like this bug is fixed! But not sure about the outstanding issue and why that could be the case (it looks like the code editor to the left is not actually accurate with what you're seeing on the right there?).

**Comment by alioguzhan** [comment] 2021-02-02 17:49
Yes, my mistake. I updated the editor code on the example page:

https://deploy-preview-105--react-editext.netlify.app/#edit-by-default

**Comment by alioguzhan** [comment] 2021-02-04 09:48
Hey @brandonparis ,

I just sent a new release to the NPM (`3.17.2`). Can you please upgrade your version? This is not a complete fix, I know. But I want to hear your feedback on real-world usage. Thanks

**Comment by alioguzhan** [comment] 2021-02-04 09:53
@all-contributors please add @brandonparis for bug report.

**Comment by brandonparis** [comment] 2021-02-04 15:01
@alioguzhan works for my use-case!

**Comment by alioguzhan** [comment] 2021-02-04 20:49
Great. I am closing this issue. I will open another issue for the remaining bug, later. Thanks for your feedback, again!

**Closed by alioguzhan** 2021-02-04 20:49 UTC
Labels: bug
