### ISSUE TITLE
Validation className

### ISSUE THREAD

**Issue by spostad7** [alioguzhan/react-editext#158] opened 2022-10-22 03:28 UTC
Thanks for this brilliant library,
I wonder how could it possible to customize validation message with className or something to style it?
I need to edit some style in validation message (font. color, ....)

**Comment by alioguzhan** [comment] 2022-10-22 08:23
Hi @spostad7 ,

You can pass a `string` or a `React Node`. In fact, anything that React can render is valid for `validationMessage`.   Both are valid below:

This: 
```jsx
<EdiText {...otherprops} validation={v => v.length > 5} validationMessage={'invalid value'} />
```

Or this:

```jsx
<EdiText 
  {...otherprops}
  validation={v => v.length > 5}
  validationMessage={<span className="invalid-value-message">Invalid Value</span>}
/>
```

Or even this:

```jsx
function renderValidationMessage() {
  return <div className="invalid-value">Invalid Value.</div>
}

<EdiText {...otherprops} validation={v => v.length > 5} validationMessage={renderValidationMessage()} />
```

**Comment by spostad7** [comment] 2022-10-22 12:54
That's perfectly fine!
Thank you for fast response

**Comment by spostad7** [comment] 2022-10-22 14:15
@alioguzhan ,
I tried the second example (using simple div element), but it seems it doesn't show any text message on the screen. It does come to DOM but the message doesn't show in the screen. Also it's notable that it insert my tag into current validation tag. I need the situation to completely overwrite current Node to my jsx element. 
here is my code so far:

```javascript
<Editor
	type="textarea"
	value={
		state.companyOverviewDescription ||
		'------'
	}
	validation={(val) =>
		val.length < descriptionLimit
	}
	validationMessage={
		<div className="invalid-feedback">
			{
				t('validation.max', {
					count: descriptionLimit
				}) as string
			}
		</div>
	}
	onSave={(val) =>
		handleUpdate({
			companyOverviewDescription: val
		})
	}
/>
```

**Comment by alioguzhan** [comment] 2022-10-22 14:32
Can you make a codesandbox reproduces this behavior, so I can check it on a full working example ?

Thanks

**Comment by alioguzhan** [comment] 2022-10-28 19:29
This is because of the same reason as #159? if so we can close this as well for now.

**Comment by spostad7** [comment] 2022-10-29 05:16
For somehow for textarea type you are correct, as you said we can not have validation on controlled save button on pressing Enter. But it's been more advance if we could completely overwrite validation tag with custom validation message rather than insert new tag into current tag, because it has its own style and may conflict with it's children style...

**Comment by alioguzhan** [comment] 2022-10-31 20:35
Ok so for backward compatibility, I can't remove the existing validation content container. But I added a new attribute `validation-container` to the validation container element. So now we can override the styles of the validation container element as well as the child content. There are already [examples in README](https://github.com/alioguzhan/react-editext#styling-with-styled-components) but here it is:

```css
div[editext='validation-container'] {
  color: #d3d3d3;
  text-decoration: underline;
}
```  

Note: `v5.1.0` is released with this update. You can upgrade the `react-editext` to test it on your local environment.

Please try this and let me know if that works.

**Comment by alioguzhan** [comment] 2022-10-31 21:00
@all-contributors add @spostad7 for ideas.

**Closed** 2022-11-04 12:57 UTC
