### ISSUE TITLE
Error: Can't resolve 'react/jsx-runtime' in '/home/pavel/projects/frontend/node_modules/react-editext/dist'

### ISSUE THREAD

**Issue by kalashnikovisme** [alioguzhan/react-editext#116] opened 2021-05-12 22:40 UTC
**Describe the bug**
1) yarn add react-editext
2) add `<EdiText value={someValue} onSave={() => console.log('save')} />` simple call to any component
3) have this error `Error: Can't resolve 'react/jsx-runtime' in '/home/pavel/projects/frontend/node_modules/react-editext/dist'`

**Expected behavior**
It should work I think

React -v 16.9.0

```
Please reproduce your problem with the below codesandbox template:

https://codesandbox.io/s/react-editext-template-5twrh

And include its URL
```

My app is very big, I think I can't reproduce it in codesandbox. Looks like this error can be fixed without sample.

**Comment by kalashnikovisme** [comment] 2021-05-12 22:48
Fixed by downgrading to version`3.18.0`

**Comment by alioguzhan** [comment] 2021-05-12 23:24
Thanks for the report. I will look into it ASAP.

**Comment by alioguzhan** [comment] 2021-05-12 23:41
I reopened this. Because this is still an issue. I am investigating. Currently, I can tell this is related to the [new jsx transform](https://reactjs.org/blog/2020/09/22/introducing-the-new-jsx-transform.html) came with react `v16.14.0`. You can downgrade the `react-editext` to `v3.18.0` or you can upgrade react and react-dom to `v16.14.0`.

I will let you know once I find out the fix. Thanks for the reporting again. @kalashnikovisme

**Comment by alioguzhan** [comment] 2021-05-13 01:11
Hey @kalashnikovisme ,

I just published a new version `4.1.4` to npm. It should be working with previous react versions. Can you please test it and verify?

Also, see this sandbox with `react v16.9.0` and `react-editext v4.1.4`:

https://codesandbox.io/s/youthful-dew-u7iv1

Feel free to close this issue once you verify that the problem is fixed.

**Comment by alioguzhan** [comment] 2021-05-13 01:15
@all-contributors add @kalashnikovisme for bug reports.

**Closed** 2021-05-22 09:24 UTC

**Comment by kalashnikovisme** [comment] 2021-06-28 01:15
@alioguzhan I've updated lib to '4.1.4'.

Everything is ok now, thanks!!
